hugoblox:
  schema: "2.0"
  identity:
    name: Stephan Scheeff
    type: person
    tagline: " Research Associate in Medicinal Chemistry Projects"
    description: Dr Stephan Scheeff is a Research Associate in Medicinal Chemistry Projects at the Chinese University of Hong Kong.
  theme:
    mode: light
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: sm
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
